### ISSUE TITLE
RuntimeException: UV_EBADF: Bad file descriptor

### ISSUE THREAD

**Issue by umbri** [amphp/amp#116]
```
PHP Fatal error:  Uncaught RuntimeException: UV_EBADF: Bad file descriptor in /home/vendor/amphp/amp/lib/Loop/UvDriver.php:49
Stack trace:
#0 [internal function]: Amp\Loop\UvDriver->Amp\Loop\{closure}(Resource id #31282, -9, 0, Resource id #29698)
#1 /home/vendor/amphp/amp/lib/Loop/UvDriver.php(163): uv_run(Resource id #25, 1)
#2 /home/vendor/amphp/amp/lib/Loop/Driver.php(127): Amp\Loop\UvDriver->dispatch(true)
#3 /home/vendor/amphp/amp/lib/Loop/Driver.php(71): Amp\Loop\Driver->tick()
#4 /home/vendor/amphp/amp/lib/Loop.php(53): Amp\Loop\Driver->run()
#5 /home/src/Server/Ampv2.php(59): Amp\Loop::run(Object(Closure))
#6 /home/examples/ampv2/server1.php(44): Empower\Server\Ampv2->listen('tcp://127.0.0.1...')
#7 {main}
  thrown in /home/vendor/amphp/amp/lib/Loop/UvDriver.php on line 49
```

1. Same tested with EvDriver and all is OK
2. Same tested with EventDriver and all is OK

**Comment by trowski** [comment]
What kind of stream are you using here? A network socket?

**Comment by umbri** [comment]
@trowski Yes

**Comment by trowski** [comment]
`UvDriver` is throwing this exception because the socket is being closed with `fclose()` while a watcher is still active in the loop for the socket, causing the internal UV event to return a status of `UV_EBADF`. Be sure to cancel all related watchers when closing a socket.

I modified the error handling when `UV_EBADF` (and other errors) is given as the event status by libuv (see the event callback [here](https://github.com/amphp/amp/blob/master/lib/Loop/UvDriver.php#L46-L57)), forwarding the exception to the loop error handler, rather than throwing the exception from the tick handler. This way such errors can be handled rather than stopping the event loop.
