### ISSUE TITLE
Coroutine objects are not destructed

### ISSUE THREAD

**Issue by umbri** [amphp/amp#117]
```
Loop::run(function ()
{
    Loop::repeat(1000, function()
    {
        print("running\n");
    });

    $res = yield new \Amp\Pause(1000, 1);

    var_dump($res);
    
    //Pause need to be __destruct-ed here!
});
```

Or I am doing something wrong ?

**Comment by bwoebi** [comment]
Try dumping the backtrace there. You'll then notice that the Pause object invokes the callbacks passed to onResolve (in this case: an internal callback passed by the Coroutine). That callback from within the Coroutine then resumes the Generator.
As you see, the Pause object obviously then still is in the backtrace and thus still exists. The Pause object will be destructed _after_ all the onResolve() callbacks have been handled.

**Comment by trowski** [comment]
I pushed an update (https://github.com/amphp/amp/commit/d01ee68dd2e55427399c78f948ab2e36291f7529) that nulls a circular reference within the Coroutine object upon resolution. This should result in immediate destruction of the Coroutine, rather than the delayed destruction that you're seeing. @umbri Try your tests again and see if memory usage is better.

**Comment by bwoebi** [comment]
The Coroutine object is still in the backtrace. And there's nothing you can do against that. It will only be freed upon return into the event loop.
Your commit (while fine) should not affect this at all.

**Comment by trowski** [comment]
@bwoebi I did some testing, and with that commit the Coroutine objects were being destructed much sooner than they otherwise would be. Try running this with and without the last commit:

```php
#!/usr/bin/env php
<?php

require __DIR__ . '/../../vendor/autoload.php';

print "-- before Loop::run()" . PHP_EOL;

function pause(int $time): \Generator {
    $res = yield Amp\call(function () use ($time) {
        return yield new \Amp\Pause($time, 2);
    });

    var_dump($res);
    return yield new Amp\Pause($time, 1);
}

Amp\Loop::run(function () {
    $res = yield new Amp\Coroutine(pause(1000));

    var_dump($res);

    $res = yield new Amp\Coroutine(pause(1000));

    var_dump($res);


    //Pause need to be __destruct-ed here!
});

print "-- after Loop::run()" . PHP_EOL;
```

Toss in a destructor on Coroutine that prints out some message. You'll see the Coroutine object destructed immediately after resolution, rather than at the end of the loop.

**Comment by umbri** [comment]
#118

**Comment by umbri** [comment]
@bwoebi @trowski I think we can close this, after running in production amp, works like a charm
