### ISSUE TITLE
What is amphp/promise? Promises/A or Promises/A+?

### ISSUE THREAD

**Issue by shtse8** [amphp/amp#150]
I am using ReactPHP/Promise now, but it is Promises/A implementation.
I would like to use Promises/A+ implementation as it has performance boost.
So what is the amphp promise? Promises/A or Promises/A+?

**Comment by kelunik** [comment]
None of them, see http://amphp.org/amp/promises/. Amp offers a single callback registration mechanism, `onResolve()`, which is optimized for coroutines. We think that coroutines are superior to callbacks.

While promises are the basic unit of concurrency, they're not the main point where to gain performance. If you want to compare due to performance concerns, I'd suggest benchmarking yourself, e.g. using [`amphp/byte-stream`](https://github.com/amphp/byte-stream/blob/master/examples/benchmark-throughput.php) vs. [`reactphp/stream`](https://github.com/reactphp/stream/blob/master/examples/benchmark-throughput.php).
