### ISSUE TITLE
Promise\all doesn't wait for all promises.

### ISSUE THREAD

**Issue by shtse8** [amphp/amp#153]
I noticed that `Promise\all` get failed once there is a promise failed. The following code will be executed without waiting all promises response (no matter failed or resolved). It really affect the flow and I can't find any good way to wait for all promises responses. I expected `Promise\all` should wait for all promises and get the result resolved when all promises are resolved, while failed when one of the promises is failed.

**Example:**
```php
use Amp\Loop;
use Amp\Deferred;
use Amp\Promise;

Loop::run(function() {
	try {
		$deferred1 = new Deferred;
		Loop::defer(function() use ($deferred1) {
			echo "1";
			$deferred1->fail(new Exception("Break the all"));
		});
		
		$deferred2 = new Deferred;
		Loop::delay(1000, function() use ($deferred2) {
			echo "2";
			$deferred2->resolve();
		});
		
		$promises = [];
		$promises[] = $deferred1->promise();
		$promises[] = $deferred2->promise();
		
		yield Promise\all($promises);
	} catch (Exception $e) {
		
	}
	echo "3";
});
```

**Expected:**
```
123
```

**Result:**
```
132
```

**Comment by shtse8** [comment]
At the moment, I can get the expected result using this instead:
```
Promise\some($promises, count($promises));
```
I have checked the source code, Promise\some has implemented correctly. But I have to pass `count($promises)` if I want to get failed on one of the promises failed every time. It's troublesome and weird.

**Comment by shtse8** [comment]
Sorry, I made some mistakes. This is the correct behavior of `all`.  But how should I if I want to wait all promises no matter they are resolved or failed? Could anyone give me an example?

**Comment by rdlowrey** [comment]
Try the `any()` function. That'll give you access to what you're looking for.

**Comment by shtse8** [comment]
`any()` will get resolved if one of the promises resolved. But I want getting resolved only when all promises are resolved. But still waiting for all promises if one's getting failed.

**Comment by kelunik** [comment]
You can just check whether there are any errors for `any` or yield `any` in a catch of `all` to wait for all remaining ones. 

What's the specific use case?

**Comment by shtse8** [comment]
Stock Market, I need to cancel all orders first and then create orders.  And many others, specially the logic flow is very important.
```php
yield cancelOrders(); // all($promises) inside
yield createOrders(); // all($promises) inside
```

If using `all`, any order is failed to be cancelled. the `all` is failed and then go to `createOrders` while other orders are still cancelling.
If using `any`, I don't want to `createOrders` if any order is failed to be cancelled. but `any` will be resolved if any one order is resolved and then go to `createOrder`.

**Comment by bwoebi** [comment]
Actually, `any()` will only get resolved, when all Promises have been resolved.

`first()` on the other hand is what you describe: gets resolved of one of the promises resolved.

The notion is `first` vs. `all` (resolve at the very first moment where it's clear that either (`first`:) _at least one_ promise succeeds or _no_ promise succeeds, or (`all`:)  _all_ promises succeed or _not all_ promises succeed. It also does resolve with just one single exception rather than giving you _all_ the values and exceptions.) and `any` vs. `some` (only resolve when **all** promises have been resolved. And they resolve with an array of exceptions and values).

There's currently no function for the special case of `some($promises, count($promises))`. (which would be basically the counterpart to any: resolve when **all** promises have been resolved _and_ throw if there was _any_ failure.)

I can see where you're coming from as the notion is quite a bit confusing due to us having two different types of behaviors for a list of four adverbs.

Perhaps it should've been called `first` vs. `every` (success notion) and `any` vs. `some` vs. `all` (resolve notion).

**Comment by shtse8** [comment]
Yes, I can understand. But no matter in which function, I need the function wait all promises responded. but not get resolved or failed once the condition is fulfilled. (e.g. `all` will be failed when any one promise failed, `first` will be resolved when any one promise succeeds.) Only `any` and `some` will wait for all promises. I suggest we should separate `wait` and `no wait` and the one as you said `first` vs `every` and `any` vs `some` vs `all`.

For some, we can do it in `no wait`, like:
```php
 --$pending;
if (\count($values) >= $required) {
	$deferred->resolve([$exceptions, $values]);
} elseif (0 === $pending) {
	$deferred->fail(new MultiReasonException($exceptions));
}
```

or `wait` version (the current version)
```php
if (0 === --$pending) {
	if (\count($values) < $required) {
		$deferred->fail(new MultiReasonException($exceptions));
	} else {
		$deferred->resolve([$exceptions, $values]);
	}
}
```

**Comment by kelunik** [comment]
I'd recommend again to just use a combination of either `all` and `any` or use `any` + a manual check whether there are any errors.
