### ISSUE TITLE
The dev version of Deferred has a different inheritance signature to live.

### ISSUE THREAD

**Issue by far-blue** [amphp/amp#155]
The Deferred class has a 'dev' and a 'production' version controlled by whether assertions are enabled. However, the Dev version has a different inheritance to the Production version and so when in Dev mode you can't use Deferred with \amp\Promise\some().

**Comment by bwoebi** [comment]
And you shouldn't. It's an optimization which saves quite some performance due to the excessive use of Promise creations in code using Amp. That's why it's production.

Generally, a Deferred is not a Promise. It gives you a Promise if you call `Deferred->promise()`. It just happens to give you an instance of itself to you in production.

So yes, you should't use the Deferred with `\Amp\Promise\some()`. If you have an array of Deferreds, you then may have to write `\Amp\Promise\some(array_map(function($deferred) { return $deferred->promise(); }, $deferreds), $requiredSuccesses)`, because - the Deferred is not a Promise. It just transparently is in production, but that's an implementation detail you ought to ignore.
