### ISSUE TITLE
stream_select error suppression

### ISSUE THREAD

**Issue by kelunik** [amphp/amp#160]
Currently we suppress errors for `stream_select`, but that might also hide useful error messages like the one shown in https://github.com/ratchetphp/Ratchet/issues/300:

```
PHP Warning:  stream_select(): You MUST recompile PHP with a larger value of FD_SETSIZE.
It is set to 1024, but you have descriptors numbered at least as high as 1123.
 --enable-fd-setsize=2048 is recommended, but you may want to set it
to equal the maximum number of open files supported by your system,
in order to avoid seeing this error again at a later date.
```

Dunno whether we can do something about that without a high performance impact.

**Comment by bwoebi** [comment]
It should be comparatively rare that stream_selects returns 0/false at all. (typically only when interrupted due to a signal, which means that it was anyway idling)

We may just check the error message at that place (right before the `return;` statement in NativeLoop) without performance penalty under normal operation.

**Comment by kelunik** [comment]
See #162 for a PR.
