### ISSUE TITLE
Loop is going wild, 100% CPU

### ISSUE THREAD

**Issue by brstgt** [amphp/amp#180]
From time to time I can see processes hanging at 100% CPU with EventDriver + Blocking FS driver (also tried ParallelDriver), strace says:
`epoll_wait(7, [], 32, 0)                = 0` in endless loop.

What all of those processes have in common: They do async HTTP with artax.

I observed a similar behaviour with NativeDriver + Parallel FS driver. This time select was looping over the same set of FDs (looked like FS worker) over and over again. But cannot tell for sure if this is the same thing.

Unfortunately there is no more information right now. Let me know if I can do sth.

**Comment by bwoebi** [comment]
A timeout of zero indicates that there are watchers enabled in every iteration of the loop. Could you please temporarily add something like `print new \Exception;` within the watcher creation/enabling methods (defer, delay, repeat, onReadable, onWritable, enable) in order to figure out what exactly is being enabled from where to have a starting point for debugging.

**Comment by brstgt** [comment]
Let me update artax + byte-stream first. I noticed it was locked to an older version due to some version restrictions in my composer file.

**Comment by kelunik** [comment]
I guess it might be https://github.com/amphp/byte-stream/releases/tag/v1.1.5 then?

**Comment by brstgt** [comment]
It looks like the update did not fix the issue. I implemented a loop breaker for debugging + added traces for watchers. Let's see if it works, the traces slow down the loop A LOT. I'll let it run over the weekend.

**Comment by brstgt** [comment]
Found the issue. It was not the fault of amps loop. It was my own custom loop decorator. Thanks anyway!
