### ISSUE TITLE
IDEA: Provide performance benchmark data

### ISSUE THREAD

**Issue by ivanjaros** [amphp/amp#191]
I have no practical experience with async PHP but I am very excited about implementing it in the near future.

One thing that I would really appreciate, as "outsider", is to see the real performance comparison with other languages and implementations(plain PHP).

Currently it seems that https://benchmarksgame.alioth.debian.org/ is the only up-to-date site that has these comparisons available.

It would be really great if someone skilled in Amp would re-implement those benchmarks into Amp and publish those numbers.

I was looking at those tests(for example https://benchmarksgame.alioth.debian.org/u64q/program.php?test=fasta&lang=php&id=3) and anybody can clearly see that there is a lot of space for improvement.

The tests they used are listed in here http://benchmarksgame.alioth.debian.org/u64q/php.html

**Comment by kelunik** [comment]
These tests won't benefit from async PHP, because they're all CPU bound tasks. Only IO bound tasks can benefit from async PHP.

We don't really like to publish benchmark results written by us, because everybody can fake their own. Benchmarks usually only show a specific minor feature being fast, but that might be misleading and totally misleading for real-world applications.

That said, I wouldn't object if someone put together some scripts that can be run and I'd merge something like that as a PR.

**Comment by ivanjaros** [comment]
> We don't really like to publish benchmark results written by us
That's why I linked to those implementation they've used. Its not about writing custom benchmarks but to implement what they've used into Amp style.

**Comment by kelunik** [comment]
The HTTP server benchmark is now included in https://github.com/TechEmpower/FrameworkBenchmarks. Other I/O bound benchmarks are welcome!
