### ISSUE TITLE
Support for Guzzle / generic promise adaption

### ISSUE THREAD

**Issue by brstgt** [amphp/amp#200]
Guzzle promises implement A+ promises but are no react promises. How about supporting them as well or more generic all vendor-promises that implement "then()"? Instead of `$result instanceof ReactPromise` you would write e.g. `isVendorPromise($result)`. `adapt()` handles any object that implements `done()` or `then()` anyway.

Any opinions?

**Comment by kelunik** [comment]
Not everything having a `then()` or `done()` method will be a promise, which might be problematic if such instances are returned from a coroutine.

For Guzzle specifically, interoperability with its promise library would be easy to add. However, interoperability with Guzzle itself isn't really sanely possible.

**Comment by brstgt** [comment]
- Of course I meant Guzzle promises, not Guzzle as a whole
- It depends on how you interpret the possible yielded values. Maybe I missed something but currently nothing but promises or arrays of promises are supported anyway. So why is it wrong to assume that anything that comes from a yield (within a coroutine) should be treated as a promise. This of course is a philosophic decision between strict typing and duck-typing principles

**Comment by kelunik** [comment]
I fully agree that it's a philosophic decision for `yield`. I'm rather worried about the `return` case, that also supports returning a promise just as `yield`, where instances that aren't promises won't error and instances that are promises are subscribed to, so the coroutine is only resolved once the returned promise resolves.

**Comment by brstgt** [comment]
Generic solution:
- define `interface PromiseAdapter`
- provide registry for `PromiseAdapters`
- `PormiseAdapters::adaptVendorPromise()` checks available adapters instead of `instanceof ReactPromise` + adapts in case of a match
- Check `instanceof \Amp\Promise` for final validity check

That creates a generic, type safe interface for promise adaption + it decouples adaption from actual adapter implementation. It also makes it extensible for further custom adapters.

**Comment by brstgt** [comment]
What do you think about that? If you basically agree on that idea, we could provide a PR for further review.

**Comment by trowski** [comment]
If we added such a registry, it would need to be used not only in coroutines, but anywhere that we currently allow React promises. Mostly this would be fine, the only place I'd be concerned about checking for vendor promises is where @kelunik alluded to: resolving promises with adaptable promises, [this line](https://github.com/amphp/amp/blob/master/lib/Internal/Placeholder.php#L107) in particular. It could be changed to `\is_object($value) && PromiseAdaptors::isVendorPromise($value)`. I don't think the impact of that would be significant enough to be a blocker here.

That being said, I wonder if it's worth baking support for further adaptations for something that seems rather niche, which already has a viable solution. You can use `Promise\adapt()` with Guzzle promises or any other A+ promise. As far as I'm aware, only Guzzle itself uses that promise library, through an API that doesn't play nice with an event loop. Is this true? Are there other promises that can be adapted?

**Comment by kelunik** [comment]
@brstgt What if two libraries define a different adapter for a specific implementation? Or do you plan that only applications make use of this new feature?

I wonder whether it's worth, given the problems above. But it made me thinking that we should maybe forbid returning promises from coroutines?

**Comment by brstgt** [comment]
Of course we had to change every occurence.
Even if react + guzzle are the only candidates at the moment it is IMHO better to have an approach that is not that tightly coupled / dependent on vendor code or if so not in so many places.
I personally don't like to have `instanceof ReactPromise` scattered over roughly 20 places.

@kelunik To avoid clashes, libraries must not implement adapters on their own. Instead they could depend on an adapter package.

If all that is too bloated, it would still be helpful to gather all the adaption code in one place and implement e.g. `\Amp\Promise\isAdaptable()` that does the instance checks and maybe support Guzzle as well.

Guzzle Promises:
We need them for async AWS client. See here: https://github.com/noerosell/awsyncronic.

Of course there are workarounds for everything but I thought the cleanest thing would be to have a generic way to support any kind of promises.

**Comment by brstgt** [comment]
@kelunik Removing support to return promises from coroutines probably breaks a lot of existing code. But I agree that it can be really confusing to allow it.

**Comment by kelunik** [comment]
I don't like the scattering either, but for one implementation it seemed acceptable. Having libraries depend on an adapter package instead of including their own adapter just moves the problem, no?

When will [this](https://github.com/noerosell/awsyncronic/blob/5476abac80a830e94a8eb3ca74d448dcd2e63484/lib/AwsLoopMiddleware.php#L18-L26) be called?

**Comment by brstgt** [comment]
@kelunik I am not really sure when this will be called. I didn't deal with that lib, yet, that's up to @bzikarsky - my co-worker

**Comment by bzikarsky** [comment]
@kelunik `AwsLoopMiddleware::runGuzzleQueue` has to be called once by the application, the naming is not perfect. `Middleware::tap` registers a synchroneous callback whenever an AWS command/request gets queued into Guzzle. This is required to make sure Guzzle starts all requests and invokes the custom handler in `AwsHttpHandler`.

**Comment by kelunik** [comment]
@brstgt It's not a problem, but at that point we can just build it into Amp itself instead of having separate packages, just like we do now for ReactPHP's promise library.

@bzikarsky As far as I can tell you need another `runGuzzleQueue()` call in a `Loop::defer()` after [that](https://github.com/noerosell/awsyncronic/blob/5476abac80a830e94a8eb3ca74d448dcd2e63484/lib/AwsHttpHandler.php#L51-L55) then to invoke the callbacks registered on the promise returned from the HTTP handler?

**Comment by brstgt** [comment]
@kelunik Actually I am totally open to any solution that helps. My 2 cents would just be:
- generic approach, no scattered vendor-related code
- if we change it anyway, we can make it extensible
- non-baked-in extensions could be managed by packages

Now it's up to you:
- do you want to support guzzle promises only
- do you support an extensible approach
- do you want us to create a PR or do it on your own
- you don't like the concept at all and ask people to use Promise\adapt() manually in application code with vendor-promises

**Comment by bwoebi** [comment]
I'd love to see a generic promise adapting approach, compatible with anything we'll do in future. The individual adapters then shall be separate from this project.

**Comment by kelunik** [comment]
@bwoebi We already have a generic adapting approach via `Amp\Promise\adapt()`. If we keep that separate (not integrated), then there's no reason for the adaption to be generic.

**Comment by trowski** [comment]
I too was never thrilled about having `instanceof ReactPromise` littered throughout the code, a generic approach seems much better, so 👍.

@brstgt If you want to provide a PR, please do.

**Comment by bwoebi** [comment]
Umm @kelunik this is not really generic, doing `instanceof ReactPromise` there. And obviously I mean internal adapting, so that you can just yield these (like the React Promises).

**Comment by kelunik** [comment]
@bwoebi There's no `instanceof ReactPromise` inside `adapt()`.

I'd like an approach that's open to future extension but doesn't allow users to register their own adapters, because changes to the supported yielded objects affect all coroutines in all packages.

Another point I just noticed we must handle: Currently neither ReactPHP nor Guzzle enforce `\Throwable` as rejection reason. Guzzle simply accepts and documents `mixed`. Currently that will result in a `TypeError` when calling `Deferred::fail()`. As Guzzle doesn't provide any `done()` method, we'll call `then()`. The promise implementation will invoke the callback, which results in the `TypeError` and the error will go unnoticed, because it just fails the promise returned from `then()`.

**Comment by bwoebi** [comment]
I'm not talking about adapt(). I'm talking about the locations _calling_ adapt() internally (e.g. in coroutines). It forces the user to call adapt() himself.

Also, allowing users to register their own adapters is no problem, as long as you register individually per class. And if you register something which is nothing promisy, that's your own fault. Nothing _we_ shall do there.

**Comment by veewee** [comment]
For what it's worth: react does a similar thing as `Amp\adapt` inside the `React\resolve` function:
https://github.com/reactphp/promise/blob/0845d291435b862f9a22bb5971ba18f50a00da09/src/functions.php#L24-L43

React supports guzzle promises, since they implement a `then` function:
https://github.com/guzzle/promises/blob/60d379c243457e073cff02bc323a2a86cb355631/src/Promise.php#L31-L53

Both react's and guzzle's `then` function return another promise.
Meaning this issue can be resolved by changing the the `Amp\adapt()` function to support the `then` method returning another promise-like object.

Currently the `Amp\adapt` function knows the promise is resolved, but doesn't pass through the return value:
https://github.com/amphp/amp/blob/eb2f325586bc6ebb12d27834fc779fa140c38a57/lib/functions.php#L336-L338


This could be changed to something like:

```php
if (\method_exists($promise, 'then')) {
    $promise->then(
        function ($result) use ($deferred): void {
            $deferred->resolve($result);
        },
        function ($failure) {
            $deferred->fail($failure instanceof \Exception ? $failure : new SomeException);
        }
    );
}
```
(we could add some safeties as you can see inside the guzzle and react codesnipptes I linked to above)

It would also open up amp to be able to pass around non-async promises (e.g. Success or Failed promise), like these:
https://github.com/azjezz/psl/blob/develop/src/Psl/Result/ResultInterface.php#L91
More info: https://github.com/azjezz/psl/pull/65#discussion_r498151955, https://github.com/azjezz/psl/issues/66

Would you be interested in a PR that contains the fix as suggested above?

**Comment by trowski** [comment]
Other than the check for a non-exception on failure, your code snippet doesn't do anything different, particularly with a return value as you seem to suggest.

If the Amp promise is being resolved with null, then that's what the adapted promise is passing to the first callback given to `then()`.

**Comment by veewee** [comment]
Woops, looks like I was confused. It indeed works as expected now that I use `onResolve(fn ($exception, $value) => ..)` instead of setting the `$value` as first argument. ... Thanks!

**Comment by kelunik** [comment]
We don't plan to support this for now.

**Comment by odahcam** [comment]
For anyone getting here nowdays, this project might be very interesting: https://github.com/amphp/http-client-guzzle-adapter
