### ISSUE TITLE
Adoption of packages

### ISSUE THREAD

**Issue by kelunik** [amphp/amp#205]
Let's discuss whether we want to adopt external packages into @amphp or not. We already adopted `amphp/ssh`, https://github.com/webgriffe/amp-csv would be another candidate.

**Comment by mmenozzi** [comment]
+1  😄

**Comment by bwoebi** [comment]
I'm fine with adopting packages for stable protocols - as long as it's fairly complete and with an easy to use API.

amp-csv in its current state - looks fairly specific (just comma+newline combination?) or do we want something more generic like getcsv()? Would also perhaps be useful to have some writer here, not only reader?

**Comment by mmenozzi** [comment]
Hi @bwoebi, amp-csv currently is in a very super alpha state.
Anyway it uses [rakdar/reactphp-csv](https://github.com/Rakdar/reactphp-csv) to parse CSV files which, in turns, should support configurable delimiter, enclosure and escape characters.

The problem is that the current implementation opens a file stream which is I/O blocking.

The idea is to refactor it using amp/file. Doing so will require us to remove the rakdar/reactphp-csv dependency and implement it on our side.

**Comment by mmenozzi** [comment]
Hi @kelunik and @bwoebi,
I've refactored [webgriffe/amp-csv](https://github.com/webgriffe/amp-csv) to remove React dependency. Now it uses only Amp packages and shouldn't be I/O blocking anymore. I think that now we should agree about the "public" API and/or implementation details. Let me know if we can discuss it here or you would like to open a dedicated issue.

Bye!

**Comment by Bilge** [comment]
What does "adopt" mean? Do you just include it within your organization's organizational structure and let the original maintainer maintain it, or do you adopt maintenance responsibility also?

**Comment by kelunik** [comment]
@Bilge It can mean either.

**Comment by Bilge** [comment]
There's quite a big difference. I don't think you should stretch yourself too thin.

**Comment by kelunik** [comment]
We won't adopt any new packages for now.

**Comment by Bilge** [comment]
You should adopt https://github.com/ScriptFUSION/Async-Throttle TBH.

**Comment by kelunik** [comment]
Throttling will be part of `amphp/pipeline` in the future.
