### ISSUE TITLE
yield VS yield from

### ISSUE THREAD

**Issue by prolic** [amphp/amp#225]
What's the difference, when to use what? Thanks.

**Comment by kelunik** [comment]
`yield` is used to "await" promises, `yield from` can be used to delegate to a sub-routine. `yield from` should only be used to delegate to private methods, any public API should always return promises instead of generators.

**Comment by prolic** [comment]
@kelunik so for example

```
public function foo(): Promise
{
    return call(function () {
        yield from $this->bar(); // I need to use yield from, because the original is yielded from a generator
    });
}

private function bar(): Generator
{
    yield 'something'; // I use simply yield here.
    yield 'something_else';
}
```

is that correct?

**Comment by prolic** [comment]
and what use-case is `return yield` needed for? Sorry to bother with rather simple questions, but the docs don't give much insight on this.

**Comment by kelunik** [comment]
@prolic Exactly, except that Amp only allows yielding promises (or arrays thereof). Instead of using `yield from`, you can also use `yield new Coroutine($this->bar());` or `yield call([$this, "bar"]);`.

`return yield` serves two purposes:
 - In case of `yield from` it results in the value being returned instead of the promise itself. Coroutines via `new Coroutine` or `Amp\call` automatically await a returned promise and return its value instead of a returned promise.
 - In case of a `try { ... } catch` block it awaits the promise and allows catching the exception in case the operation fails.

I hope that helps. If you have suggestions how to improve the documentation for newcomers, PRs are always welcome!

**Comment by prolic** [comment]
@kelunik Thanks a lot, I think that clarifies it a little. Let me submit a PR incl. some simple examples this weekend.

**Comment by prolic** [comment]
see https://github.com/amphp/amp/pull/226

**Comment by prolic** [comment]
I hope it's correct, please correct any errors :)
