### ISSUE TITLE
CountdownEvent & ManualResetEventSlim

### ISSUE THREAD

**Issue by prolic** [amphp/amp#244]
I got this idea from C#, where it is used for threads, however I found it quite useful for amp as well.

See:
https://github.com/prooph/event-store-client/blob/master/tests/CountdownEvent.php
and
https://github.com/prooph/event-store-client/blob/master/src/Internal/ManualResetEventSlim.php

if you like this idea, I can provide a PR.

**Comment by prolic** [comment]
@bwoebi about ManualResetEventSlim: Basically yes, but it removes a lot of boilerplate to write.

F.e. in a subscription you can do this in constructor:

`$this->stopped = new ManualResetEventSlim(true);`

then when subscription was dropped this:

`$this->stopped->set();`

when start() is called:

`$this->stopped->reset();`

and when you call stop(int $timeout) you do this:

`return $this->stopped->wait($timeout);`

The set / reset methods are easily replaced with resetting a deferred and resolving with true value, so there is not `that` much benefit, but the wait method is really some boilerplate to write everywhere.

To me it is also very useful in testing, because I don't need to write this `wait` boilerplate all over the tests again and again.

However, if you don't want to have it, I'm okay with providing a PR only for CountdownEvent - do you like the implementation as is or do you want any changes before before I send the PR?

**Comment by bwoebi** [comment]
I do agree that wait() is quite a bit of boilerplate, but the main issue is that we have no timeout function which simply resolves with a default value and instead always throws.

I think it could be worth adding a timeout function to amp, which simply resolves to a deferred with a value (given as argument) instead of throwing. I've also missed that multiple times and ended up writing a boilerplate one-off Loop::delay() instead.

This would also effectively reduce your wait boilerplate to `timeoutWithDefault($this->stopped->promise(), false)`.

**Comment by prolic** [comment]
Okay, sounds good, I will provide a PR this weekend.
Sascha-Oliver Prolic


Am Mi., 31. Okt. 2018 um 17:47 Uhr schrieb Bob Weinand <
notifications@github.com>:

**Comment by kelunik** [comment]
Closing, as https://github.com/amphp/sync/pull/9 and https://github.com/amphp/amp/pull/245 have been merged.
