### ISSUE TITLE
PHP async call

### ISSUE THREAD

**Issue by coinbreze** [amphp/amp#312]
Hi,

Kindly help me.

In below sample function same time same record getting affected multiple times, if I call updateData() through  multi curl or any tool. I have used asyncCall method from amphp but still same issue occur if I call ampCall() function through tool.

@kelunik Kindly do the needful to overcome the issue using amphp

PHP version 7.0.33
```
function ampCall(){
 asyncCall(function () use(){
   		yield new Delayed(400);
		$response = $this->updateData();
 });
}
Loop::run();

```
example
```
function updateData(){
	if(find value if data equal 1){
		update the data to 2
		insert new record
	}
}
```

**Comment by kelunik** [comment]
Hey @coinbreze,

I'm not sure where CURL gets involved here exactly, but generally CURL and Amp aren't compatible, because CURL doesn't work with `stream_select` and blocks on I/O. `asyncCall` won't make your blocking I/O magically non-blocking and work in an event loop.

However, depending on your goals, [`amphp/parallel`](https://github.com/amphp/parallel) might be an option to offload these blocking calls into worker threads, while using only non-blocking I/O in the parent process. Another option is to replace your CURL and database calls with non-blocking implementations such as [`amphp/http-client`](https://github.com/amphp/http-client) and [`amphp/mysql`](https://github.com/amphp/mysql).
