### ISSUE TITLE
Functions should require callable instead of closures

### ISSUE THREAD

**Issue by ostrolucky** [amphp/amp#415]
I like using invokable objects, but these are not possible to use with Amp functions, like `\Amp\async` and so on without casting. Can we relax `\Closure` type requirement to `callable` instead?

**Comment by trowski** [comment]
We chose `Closure` for a few reasons:
- The `callable` type in PHP is scope-dependent. What is callable in one scope may not be callable when attempting to invoke it from another scope (Luckily this problem will go away in PHP 9: https://wiki.php.net/rfc/deprecate_partially_supported_callables) _(EDIT: I was wrong, that RFC does not completely clean up scope issues, visibility problems can still happen with `callable`, but cannot with `Closure`.)_
- `callable` cannot be used as a class property (largely due to the above), so is more cumbersome to use.
- First-class callable syntax makes it easy to create closures. `[$this, 'method']` being a "callable" has always been strange IMO. `$this->method(...)` is far superior, clearly indicating that a closure is being created.
- Using `Closure` does allow us to widen the type to `callable` at a later time without BC breaks

Invokable objects unfortunately suffer because of this decision. First-class callable syntax does work with invokable objects. `async($object(...))` is clear that the intention is to pass a closure to be called. `async($object)` may be be confused for passing the object to be manipulated or a mistake if `$object` were not an invokable object.

I'm willing to consider changing `Closure` to `callable` in the future, but for the near term I think I'd like to keep `Closure`.

**Comment by ostrolucky** [comment]
Fair enough, although I don't see how any of those 2 disadvantages are a factor for util functions. First one is more for authors of callables (me), second one for classes, while amp util functions are not classes. But of course, my position is purely from trying to have slightly nicer syntax. `$object->method(...)` looks fine in such trivial example, but what about multi line calls?  With callables accepted, I could do

with callables accepted, I could do
```php
async(new Responder(
    $logger,
    $bufferer,
    $output,
    $this->customHttpHeaders,
    new ResourceInputStream(fopen($bufferer->filePath, 'rb')),
    $newConnDefer
));
```

without them, I have to do either
```php
async((new Responder(
    $logger,
    $bufferer,
    $output,
    $this->customHttpHeaders,
    new ResourceInputStream(fopen($bufferer->filePath, 'rb')),
    $newConnDefer
))(...));
```

or 
```php
$responder = new Responder(
    $logger,
    $bufferer,
    $output,
    $this->customHttpHeaders,
    new ResourceInputStream(fopen($bufferer->filePath, 'rb')),
    $newConnDefer
);
async($responder(...));
```

and I'm not a fan of either. But again, it's something we all can live with, just adding my suggestion for minor improvement.

**Comment by Bilge** [comment]
```php
async(fn () => new Responder(
    $logger,
    $bufferer,
    $output,
    $this->customHttpHeaders,
    new ResourceInputStream(fopen($bufferer->filePath, 'rb')),
    $newConnDefer
));
```

**Comment by ostrolucky** [comment]
Indeed, I think that one is good enough. Alright let's close then :)

**Comment by ostrolucky** [comment]
Actually, in my cases I also need to pass arguments to Responder so above wouldn't work. with callable support I would be able to do
```php
async(
  new Responder(
    $logger,
    $bufferer,
    $output,
    $this->customHttpHeaders,
    new ResourceInputStream(fopen($bufferer->filePath, 'rb')),
    $newConnDefer
  ),
  $socket,
); 
```

but with arrow functions it would be
```php
async(
  fn($arg) => (new Responder(
    $logger,
    $bufferer,
    $output,
    $this->customHttpHeaders,
    new ResourceInputStream(fopen($bufferer->filePath, 'rb')),
    $newConnDefer
  ))($arg),
  $socket,
); 
```

which doesn't bring benefit over
```php
async(
  (new Responder(
    $logger,
    $bufferer,
    $output,
    $this->customHttpHeaders,
    new ResourceInputStream(fopen($bufferer->filePath, 'rb')),
    $newConnDefer
  ))(...),
  $socket,
); 
```

**Comment by Bilge** [comment]
What in the hell are you talking about?

**Comment by Bilge** [comment]
https://3v4l.org/dO0Me

**Comment by ostrolucky** [comment]
Yes but that's arguably worse than https://3v4l.org/ZePLZ (desired) or https://3v4l.org/GZ5C8 (`(...)` syntax)

**Comment by Bilge** [comment]
Stop trying to code other people's libraries for them.

**Comment by ostrolucky** [comment]
Well, this doesn't look like it's going to be a productive discussion. Sorry that my fresh feedback from amp 2.x -> 3.x update experience bothered you. I was used to pass callable to asyncCoroutine, but this is no longer accepted. All I'm saying is I would prefer if I could still pass callables, because it's more flexible and has nicer syntax, that's it.

**Comment by xpader** [comment]
I also prefer to use callable, in amp v2, I have lots of code like `call([$target, 'wakeup'])`,  but in php8.1, first-class callable syntax is acceptable as an alternative `async($target->wakeup(...))`.

In your example, a callable object implement __invoke is useful, but it's not commonly used.

```php
class CallableThing {

    public function __invoke()
    {
    }

}

$callableThing = new CallableThing();
$callableThing();

```

So, for now, I think you should accept first-class callable syntax or use closure fn().
