### ISSUE TITLE
setErrorHandler doesn't make sense as coroutine?

### ISSUE THREAD

**Issue by kelunik** [amphp/amp#51]
[`setErrorHandler`](https://github.com/amphp/amp/blob/7f5142be8853fd7131fb9914aba3a29aed9602b3/lib/functions.php#L215-L229) is currently executed as coroutine, I don't know whether that really makes sense, as exceptions either have to be rethrown to stop the loop or not rethrown to continue. Having a coroutine there, makes the loop always continue.

**Comment by rdlowrey** [comment]
How would I log information about the error that occurred (via network IO) when I don't want the loop to stop otherwise? The goal of the error handler is to give applications control over whether they want the loop to be broken (one of the biggest pain points in node applications where servers would just die).

**Comment by kelunik** [comment]
@rdlowrey You can just start a coroutine inside the handler. But the handler itself needs a direct continue or not. It can't wait for the coroutine to finish.

**Comment by kelunik** [comment]
Closing, as the proxy functions are no longer a thing.
